# Generated by Django 2.1.7 on 2019-03-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_matches', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=5)),
                ('team0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_matches.Team')),
            ],
        ),
    ]
