# Generated by Django 2.1.7 on 2019-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_matches', '0003_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team0',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='search_matches.Team'),
        ),
    ]
