# Generated by Django 2.1.7 on 2019-03-16 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_matches', '0004_auto_20190315_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
