# Generated by Django 2.1.7 on 2019-03-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_matches', '0005_match_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
    ]
